name: Podcast Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # 每天 0 点自动运行

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sync:
    name: Sync Podcast Data
    runs-on: ubuntu-latest

    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTION_PAGE: ${{ secrets.NOTION_PAGE }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install notion-client==1.0.0  # 确保 Notion SDK 使用新版接口

      - name: Run podcast sync script
        run: |
          python -u scripts/podcast.py
